#工程的配置文件
server:
  port: 8081
  servlet:
    context-path: /manager
#配置 mybatis-config.xml 路径，mybatis-config.xml 中配置 MyBatis 基础属性
mybatis:
  mapper-locations: mapper/*.xml
  type-aliases-package: com.kk.Springbootmanger.domain
  #配置sql的打印 //包路径为mapper文件包路径
  configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


#数据库的配置信息
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
